In [1]:
print('fit a model with', 11, 'variables')

fit a model with 11 variables


In [2]:
#print?

In [3]:
3 +5

8

In [4]:
"hello" + " " + "world"

'hello world'

In [5]:
x=[3,4,5]
x

[3, 4, 5]

In [6]:
y=[4,9,7]
x+y

[3, 4, 5, 4, 9, 7]

In [7]:
import numpy as np


In [8]:
x=np.array([3,4,5])
y=np.array([4,9,7])

In [9]:
x+y

array([ 7, 13, 12])

In [10]:
#2D array
x= np.array([[1,2],[3,4]])
x

array([[1, 2],
       [3, 4]])

In [11]:
x.ndim

2

In [12]:
x.dtype

dtype('int32')

In [13]:
np.array([[1,2], [3.0,4 ]]).dtype

dtype('float64')

In [14]:
x.shape

(2, 2)

In [15]:
x=np.array([1,2,3,4])
x.sum()

10

In [16]:
x=np.array([1,2,3,4,5,6])
print('beginning x: \n',x)
x_reshape = x.reshape(2,3)
print('reshaped x:\n', x_reshape)

beginning x: 
 [1 2 3 4 5 6]
reshaped x:
 [[1 2 3]
 [4 5 6]]


In [17]:
x_reshape.shape,x_reshape.ndim,x_reshape.T

((2, 3),
 2,
 array([[1, 4],
        [2, 5],
        [3, 6]]))

In [18]:
np.sqrt(x)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974])

In [19]:
x**2

array([ 1,  4,  9, 16, 25, 36])

In [20]:
x**0.5

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974])

In [21]:
x= np.random.normal(size=50)
x

array([-1.28380827,  0.1750162 , -0.20099318,  0.22983855,  0.38856444,
        1.29679255,  0.06855814, -0.82544017, -0.01482704, -1.68672446,
        0.40054596, -0.24887152, -1.74624797, -1.00200809,  0.06857966,
        0.16170804, -0.72462302, -0.55588438,  1.03057002,  0.44764235,
        0.42764537, -0.25064792, -0.83770525,  0.88661263, -0.29192722,
       -0.52838717, -1.17579393,  1.133556  ,  1.75693014,  0.37031717,
        0.10625465,  0.59084135, -2.40024959, -1.40630141, -1.92474583,
        1.51106864,  1.26916361, -1.71592631,  0.51185305, -0.28025068,
        2.01972962, -0.32344638, -2.13592124, -0.04415109, -0.31347264,
       -1.21291671, -0.24224666,  0.64206738, -0.35253401,  0.64336858])